// Explicit local E2E smoke. Creates ONE synthetic QA account in the local database.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const base = process.env.QA_BASE_URL || 'http://127.0.0.1:8022';
assert.ok(['localhost', '127.0.0.1'].includes(new URL(base).hostname));
const dir = path.resolve('tmp/ui-ux-qa');
fs.mkdirSync(dir, { recursive: true });
(async () => {
  const browser = await chromium.launch({ headless: true, ...(process.env.CHROME_BIN ? { executablePath: process.env.CHROME_BIN } : {}) });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultTimeout(10000);
  const report = { scope: 'Real local HTTP calls; DEMO server is not proof of production model inference', stages: [], responses: [], errors: [] };
  const mark = name => { report.stages.push(name); console.log(`PASS ${name}`); };
  const email = `uiqa-${Date.now()}@example.com`;
  const password = 'LocalQa123!';
  page.on('response', response => { const url = new URL(response.url()); if (url.pathname.startsWith('/api/v1/')) report.responses.push({ path: url.pathname, status: response.status() }); });
  page.on('pageerror', error => report.errors.push(error.message));
  try {
    await page.goto(base, { waitUntil: 'domcontentloaded' });
    await page.locator('#sidebar-signup').click();
    await page.locator('#email').fill(email);
    await page.locator('#password').fill(password);
    await page.locator('#signup-birth-date').fill('1966-04-12');
    await page.locator('#personal-consent').check();
    await page.locator('#health-consent').check();
    await page.locator('#signup-form button[type="submit"]').click();
    await page.locator('.screen[data-step="3"].active').waitFor();
    mark('signup -> automatic login -> profile/consent -> eligibility');
    // Verify returning account without health records using a fresh page, no shared app state.
    const returning = await browser.newPage();
    await returning.goto(base, { waitUntil: 'domcontentloaded' });
    await returning.locator('#sidebar-login').click();
    await returning.locator('#login-email').fill(email);
    await returning.locator('#login-password').fill(password);
    await returning.locator('#login-form button[type="submit"]').click();
    await returning.locator('.screen[data-step="3"].active').waitFor({ timeout: 10000 });
    mark('login without health history -> eligibility, not empty dashboard');
    await returning.close();
    await page.locator('label').filter({ has: page.locator('input[name="urgent-warning"][value="no"]') }).click();
    await page.locator('label').filter({ has: page.locator('input[name="diabetes-diagnosis"][value="no"]') }).click();
    await page.locator('#eligibility-form button[type="submit"]').click();
    await page.locator('.screen[data-step="4"].active').waitFor();
    mark('eligible adult -> health input');
    await page.locator('#height').fill('170');
    await page.locator('#weight').fill('70');
    await page.locator('#to-lifestyle-input').click();
    await page.setViewportSize({ width: 380, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    await page.screenshot({ path: path.join(dir, 'lifestyle-mobile.png'), fullPage: true });
    await page.locator('#to-detail-input').click();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    await page.locator('[data-health-tab="review"]').click();
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.screenshot({ path: path.join(dir, 'input-review-desktop.png'), fullPage: true });
    mark('basic -> lifestyle -> detail -> review; 380px input pages fit');
    await page.locator('#submit-analysis').click();
    await page.waitForFunction(() => state.step === 6 || (state.step === 5 && !document.querySelector('#retry-analysis').hidden), { timeout: 45000 });
    if (await page.evaluate(() => state.step) !== 6) throw new Error('Analysis did not succeed; retry state visible');
    mark('health save -> analysis -> result');
    await page.screenshot({ path: path.join(dir, 'result-desktop.png'), fullPage: true });
    await page.locator('#to-challenges').click();
    await page.locator('.screen[data-step="7"].active').waitFor();
    await page.locator('[data-challenge-category="activity"]').click();
    await page.locator('.challenge-detail-option').first().click();
    await page.locator('#start-challenge').click();
    await page.locator('.screen[data-step="8"].active').waitFor();
    mark('result -> challenge selection -> cycle creation -> dashboard');
    await page.screenshot({ path: path.join(dir, 'dashboard-desktop.png'), fullPage: true });
    const saved = await browser.newPage();
    await saved.goto(base, { waitUntil: 'domcontentloaded' });
    await saved.locator('#sidebar-login').click();
    await saved.locator('#login-email').fill(email);
    await saved.locator('#login-password').fill(password);
    await saved.locator('#login-form button[type="submit"]').click();
    await saved.locator('.screen[data-step="8"].active').waitFor({ timeout: 10000 });
    mark('login with saved health history -> dashboard');
    await saved.close();
    assert.deepEqual(report.errors, []);
  } catch (error) {
    report.blocker = error.message;
    report.screen = await page.locator('.screen.active').innerText().catch(() => 'unavailable');
    await page.screenshot({ path: path.join(dir, 'flow-blocker.png'), fullPage: true });
    console.error(`BLOCKED ${error.message}`);
    process.exitCode = 1;
  } finally {
    fs.writeFileSync(path.join(dir, 'live-flow.json'), JSON.stringify(report, null, 2));
    await browser.close();
  }
})();
