const state = {step:1, token:null, checkupId:null, predictionId:null, factors:[], challenges:[], cycle:null};
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const stageLabels = {normal:"일반 관심 단계", prediabetes:"주의 관찰 단계", diabetes_screening_advised:"검사 상담 권고 단계"};

function showMessage(message){const box=$("#message");box.textContent=message;box.hidden=false;box.scrollIntoView({behavior:"smooth",block:"center"});}
function clearMessage(){$("#message").hidden=true;}
function showStep(step){state.step=Math.max(1,Math.min(8,step));clearMessage();$$('.screen').forEach(el=>el.classList.toggle('active',Number(el.dataset.step)===state.step));$$('#step-list li').forEach((el,i)=>{el.classList.toggle('active',i+1===state.step);el.classList.toggle('complete',i+1<state.step)});$('#step-current').textContent=state.step;$('#progress-bar').style.width=`${state.step/8*100}%`;window.scrollTo({top:0,behavior:'smooth'});}
async function api(path, options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const response=await fetch(`/api/v1${path}`,{...options,headers});let payload={};try{payload=await response.json()}catch{}if(!response.ok)throw new Error(payload.detail||payload.error?.message||'요청을 처리하지 못했습니다.');return payload.data??payload;}
function formBoolean(id){return $(id).checked;}

$$('.next').forEach(button=>button.addEventListener('click',()=>showStep(state.step+1)));
$$('.back').forEach(button=>button.addEventListener('click',()=>showStep(state.step-1)));
$('#font-toggle').addEventListener('click',(event)=>{const enabled=document.body.classList.toggle('large-text');event.currentTarget.setAttribute('aria-pressed',String(enabled));event.currentTarget.textContent=enabled?'기본 글자':'글자 크게';});

$('#signup-form').addEventListener('submit',async(event)=>{event.preventDefault();try{const signup=await api('/auth/signup',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value,terms_agreed:true})});state.token=signup.access_token;await api('/consents',{method:'POST',body:JSON.stringify({consent_item:'health_data',version:'1.0',is_agreed:true})});showStep(3)}catch(error){showMessage(error.message)}});

$('#eligibility-form').addEventListener('submit',async(event)=>{event.preventDefault();try{const result=await api('/eligibility-checks',{method:'POST',body:JSON.stringify({birth_date:$('#birth-date').value,has_diabetes_diagnosis:formBoolean('#diagnosed-diabetes'),has_hypertension_diagnosis:formBoolean('#diagnosed-hypertension'),uses_glucose_lowering_drug:formBoolean('#glucose-drug'),has_alarming_symptom:formBoolean('#alarming'),has_exercise_limitation:false})});if(!result.is_eligible){showMessage(`${result.exclusion_reasons.join(', ')}: ${result.guidance}`);return}showStep(4)}catch(error){showMessage(error.message)}});

$('#health-form').addEventListener('submit',async(event)=>{event.preventDefault();const submit=event.submitter;submit.disabled=true;submit.textContent='계산 중…';try{const checkup=await api('/health-checkups',{method:'POST',body:JSON.stringify({checkup_type:'initial',checkup_date:new Date().toISOString().slice(0,10),gender:$('#gender').value,height_cm:Number($('#height').value),weight_kg:Number($('#weight').value),waist_cm:Number($('#waist').value),systolic_bp:Number($('#systolic').value),diastolic_bp:Number($('#diastolic').value),fasting_glucose:$('#glucose').value?Number($('#glucose').value):null,smoking_status:$('#smoking').value,drinking_frequency:'monthly_or_less',physical_activity_level:$('#activity').value,has_family_history_diabetes:formBoolean('#family-history')})});state.checkupId=checkup.checkup_id;const job=await api('/prediction-jobs',{method:'POST',body:JSON.stringify({checkup_id:state.checkupId,disease_type:'diabetes'})});state.predictionId=job.prediction_id;const [prediction,factors]=await Promise.all([api(`/predictions/${state.predictionId}`),api(`/predictions/${state.predictionId}/risk-factors`)]);state.prediction=prediction;state.factors=factors.items;renderResult();showStep(5)}catch(error){showMessage(error.message)}finally{submit.disabled=false;submit.textContent='위험 단계 확인'}});

function renderResult(){const p=state.prediction;$('#result-stage').textContent=stageLabels[p.predicted_stage]||p.predicted_stage;$('#result-explain').textContent=p.model_notice;$('#risk-score').textContent=`${Math.round(p.risk_score*100)}점`;$('#score-ring').style.background=`conic-gradient(var(--green) ${p.risk_score*100}%,#cddbd6 0)`;const labels={normal:'일반 관심',prediabetes:'주의 관찰',screening_advised:'검사 상담 권고'};$('#probabilities').innerHTML=Object.entries(p.probabilities).map(([key,value])=>`<div class="prob-row"><strong>${labels[key]}</strong><div class="bar"><span style="width:${value*100}%"></span></div><span>${Math.round(value*100)}%</span></div>`).join('');$('#factor-list').innerHTML=state.factors.map(f=>`<li><span class="factor-icon ${f.direction}">${f.direction==='protective'?'✓':'!'}</span><div><strong>${f.factor_name}</strong><p>${f.description}</p></div></li>`).join('');}

$$('.screen[data-step="6"] .next').forEach(button=>button.addEventListener('click',loadChallenges,{once:true}));
async function loadChallenges(){try{const result=await api(`/challenge-recommendations?prediction_id=${state.predictionId}`);state.challenges=result.items;$('#challenge-list').innerHTML=state.challenges.map((item,i)=>`<label class="challenge-card"><input type="checkbox" name="challenge" value="${item.challenge_id}" ${i===0?'checked':''}><span><strong>${item.title}</strong><small>목표: ${item.daily_goal}</small><small>${item.reason}</small></span></label>`).join('')}catch(error){showMessage(error.message)}}

$('#challenge-form').addEventListener('submit',async(event)=>{event.preventDefault();const ids=$$('input[name="challenge"]:checked').map(input=>Number(input.value));if(!ids.length){showMessage('챌린지를 하나 이상 선택해 주세요.');return}try{state.cycle=await api('/challenge-cycles',{method:'POST',body:JSON.stringify({prediction_id:state.predictionId,challenge_ids:ids})});renderDashboard();showStep(8)}catch(error){showMessage(error.message)}});

function renderDashboard(){const cycle=state.cycle;$('#dashboard-stage').textContent=stageLabels[state.prediction.predicted_stage];$('#dashboard-cycle').textContent=`1주차 / 4주`;$('#daily-log-list').innerHTML=cycle.user_challenges.map(item=>`<label class="daily-item"><input type="checkbox" name="daily" value="${item.user_challenge_id}"><span>${item.title}</span></label>`).join('');refreshDashboard();}
async function refreshDashboard(){try{const summary=await api('/dashboard/summary');$('#dashboard-complete').textContent=`${summary.challenge_completion.completed_logs}개`}catch(error){showMessage(error.message)}}
$('#daily-log-form').addEventListener('submit',async(event)=>{event.preventDefault();try{const today=new Date().toISOString().slice(0,10);await Promise.all($$('input[name="daily"]').map(input=>api(`/user-challenges/${input.value}/logs/${today}`,{method:'PUT',body:JSON.stringify({is_completed:input.checked,note:null})})));await refreshDashboard();showMessage('오늘 기록을 저장했습니다.');$('#message').style.background='#e9f4f0';$('#message').style.color='#0b4d42'}catch(error){showMessage(error.message)}});
$('#restart').addEventListener('click',()=>location.reload());
